### ISSUE TITLE
[FEATURE] start imediatly after manual title selection

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#10]
### Description
it would be nice to have a job start imediatly after the title has been manualey selected or with a short configurable delay.

**Comment by 1337-server** [comment]
I havent tested this but this might work.

```
    #  If we have have waiting for user input enabled
    if job.config.MANUAL_WAIT:
        logging.info("Waiting " + str(job.config.MANUAL_WAIT_TIME) + " seconds for manual override.")
        job.status = "waiting"
        db.session.commit()
        sleep_time = 0
        while sleep_time < job.config.MANUAL_WAIT_TIME:
            time.sleep(5)
            sleep_time += 5
            db.session.refresh(job)
            db.session.refresh(config)
            if job.title_manual:
                break
        # db.session.refresh(job)
        # db.session.refresh(config)
        job.status = "active"
        db.session.commit()
```

instead of (in main.py)
```
    #  If we have have waiting for user input enabled
    if job.config.MANUAL_WAIT:
        logging.info("Waiting " + str(job.config.MANUAL_WAIT_TIME) + " seconds for manual override.")
        job.status = "waiting"
        db.session.commit()
        time.sleep(job.config.MANUAL_WAIT_TIME)
        db.session.refresh(job)
        db.session.refresh(config)
        job.status = "active"
        db.session.commit()
```
They isnt really an easy way to cancel the time.sleep that i know of. And this may add to the problem of multiple sources trying to access the db causing the db locked error. 

I will try to test this when i get some more free time.

**Comment by TomW1605** [comment]
given that you are only reading from the database i think that should be fine

**Comment by TomW1605** [comment]
ok i worked out another way. leave the sleep alone but after it is done have it check to see if the job is active before making it active. then you can just have the manual update script set it as active without interrupting the sleep (but probably with the same "is active" check). this would mean at most 2 database calls instead of doing it every 5 seconds.

**Comment by 1337-server** [comment]
Do you mean just setting the job.status label to active ?

Because thats much much easier. I maybe have misunderstood, i thought you meant to force the job to stop the sleep and continue processing. 
Setting/updating the job.status is really simple, and can be updated via the ui when you update the job.

**Comment by TomW1605** [comment]
im not really sure. i think you would take everything after [here](https://github.com/1337-server/automatic-ripping-machine/blob/v2.4_dev/arm/ripper/main.py#L163) and put it in a new function. then have both the manual name change ui and the timer call that function after checking the job status. but i have no idea if that would work or if you could get the right values to the right place

**Comment by 1337-server** [comment]
The problem is by the time the user reaches that line, ARM has already waited the full wait period. 
Because as soon as they hit 
[158](https://github.com/1337-server/automatic-ripping-machine/blob/1f219d553cd68a04f4929631922b863df7251c6e/arm/ripper/main.py#L158)`time.sleep(job.config.MANUAL_WAIT_TIME)`
ARM will wait for the full timer. No matter what happens.

Thats why i thought of maybe checking in set intervals, possibly even using the [utils.database_updater function](https://github.com/1337-server/automatic-ripping-machine/blob/1f219d553cd68a04f4929631922b863df7251c6e/arm/ripper/utils.py#L1323) with some slight changes to use the  db.session.refresh() ? That should stop any locking of the database.

I will for sure have a proper look at this, as its a really good idea. Unless you want to try and let me know if you get it work ?

**Comment by TomW1605** [comment]
i might have a go but i think i will probably break it as i dont yet understand the data flow properly.

**Comment by 1337-server** [comment]
This may help https://github.com/1337-server/automatic-ripping-machine/wiki/workflow-diagram

**Comment by TomW1605** [comment]
unfortunately that does not include manual name overrides.

**Comment by 1337-server** [comment]
Could you explain a little more what you need ?

**Comment by TomW1605** [comment]
not yet. i will have a look on the week end but till then i dont know what i dont know

**Comment by 1337-server** [comment]
Feature is now added

**Comment by TomW1605** [comment]
who did you go about doing it?

**Comment by 1337-server** [comment]
I used the code posted above.
It worked great for me, but i only have 3 drives to test with. 
So it may not be perfect for larger numbers.

**Comment by TomW1605** [comment]
ok cool. i only have 1 drive at the moment so cant help much with testing more drives. i do have about 10 spare sata dvd drives but i can only pass 2 sata ports through to the VM. i might set up a dedicated machine with more drives but i dont have the hardware for that right now

**Comment by 1337-server** [comment]
Its all good man. Thanks for the help so far!
