### ISSUE TITLE
[Question] Plans

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#11]
what are your plans with this fork? do you intend to eventually make a massive pull request to the official repo or just keep going alone?

**Comment by 1337-server** [comment]
I have tried submitting Pull Request to the main repo, as it was my intention just use this fork to get the main repo updated. 

However i'm not sure if anyone is active on the main project, the PR i already made has been stale for some time and the main v2.4_dev branch is significantly more updated than even my stale PR.  Hopefully the main repo becomes more active soon. And once my initial PR either gets merged or rejected i will submit a PR from the v2.4_dev branch.

It would be nice to have all these changes on the main repo, so that more users could access some of the new features and bugfixes. But its not something i can control.

**Comment by TomW1605** [comment]
fair enough. i have a habit of looking at the network graph for projects that look a bit stale and then working off the most recently updated repo, in this case yours.

**Comment by 1337-server** [comment]
That's probably the best way to do it. I didnt pay attention/didnt know about checking forks for updates as i was new to github.
And ended up doing some things that had already been done in some of the forks.

It was only recently that i started checking the most active forks for any new features/ideas that might be good to add to ARM.

**Comment by 1337-server** [comment]
Closing this now as the main ARM repo is active again.

**Comment by TomW1605** [comment]
great hope all this stuff gets merged
