### ISSUE TITLE
Files placed in movies folder while still transcoding.

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#17]
### Description
files are placed in the movies folder as the transcode destination but this makes it hard to know what ones are finished and ready to be sorted. is it possible to have a folder that they get moved into as the last thing once they are finished?

i would suggest a file structure like this
```
ARM/
├─ complete/
│  ├─ movies/
│  ├─ tv/
│  ├─ unmatched/
├─ raw/
├─ transcode/
│  ├─ movies/
│  ├─ tv/
│  ├─ unmatched/
```
this way the raw folder stays what it is now, the movie folder becomes the transcode folder and has subfolders for movies, tv and unmatched transcodes and the compleat folder (i think this used to be for unmatched transcodes) is where items are moved as the last step of the script.

**Comment by 1337-server** [comment]
This is already possible thanks to the way ARM is setup. But it would need slight changes to the main.py.

ARM was originally coded to put all files into a non final directory, and then when complete it would move the files if the movie/series was identified and has a nice title. But this code was never finished and all items went to the unidentified folder.

Currently ARM starts the job and creates the folders here https://github.com/1337-server/automatic-ripping-machine/blob/704457fa099af43f4881fd135f5b5ca2963fdc11/arm/ripper/main.py#L214
or here
https://github.com/1337-server/automatic-ripping-machine/blob/704457fa099af43f4881fd135f5b5ca2963fdc11/arm/ripper/main.py#L231

and once processing completes they are checked and moved from this line
https://github.com/1337-server/automatic-ripping-machine/blob/704457fa099af43f4881fd135f5b5ca2963fdc11/arm/ripper/main.py#L391

The problem is that there is no move because of the changes i made around the first 2 lines i posted. The first 2 lines place the files in the final directory. A simple change is to place them in the `ARMPATH` and ARM will now move them to the `MEDIA_DIR` when the job is finished.

I do much prefer the planned layout you have posted. Its much cleaner!

**Comment by TomW1605** [comment]
i will look into it. also is there a reason those first 2 lines are different? they do the same thing just one has a time stamp. why use different ways to build the string?

**Comment by 1337-server** [comment]
The first line is if there are no no folders matching the Movie title. The second if for if there is a folder already created. It tries to add a unuiqe number to the end of the file name.

**Comment by TomW1605** [comment]
i cant actualy work out the point of the second part at all. why not just take the path made the first time and add a random number to that instead of starting again from scratch?

**Comment by 1337-server** [comment]
Its not something i had really given much thought to be honest.

**Comment by TomW1605** [comment]
ok i think i have this working. it is not deleting the folder from the transcode path but that is easy to fix. the only problem is it requires some database changes because it needs different config variables

**Comment by TomW1605** [comment]
but it is transcoding into the transcode directory and then moving into the compleat directory when doen and separating tv and movies into subfolders in those directories. im not sure there needs to be subfolders in the the transcode directory, what do you think?)

**Comment by 1337-server** [comment]
> 
> 
> it is not deleting the folder from the transcode path but that is easy to fix. 

This is because of my hackish soloution of ` if hboutpath != final_directory: ` to stop ARM removing the final directory.

**Comment by TomW1605** [comment]
ah i was wondering what that was for. i will have a look at that part of the code and see if i can fix it.

**Comment by TomW1605** [comment]
ok there is a `move_files` [function](https://github.com/1337-server/automatic-ripping-machine/blob/d33899f291683609222f1e27836126f6bdd0fb7c/arm/ripper/utils.py#L815) and a `rename_files` [function](https://github.com/1337-server/automatic-ripping-machine/blob/d33899f291683609222f1e27836126f6bdd0fb7c/arm/ripper/utils.py#L913) but they both do basicaly the same thing from what i can tell. only diffrance is the processing they do to genarate the destination path. would it not be better to just have a move function that takes a source and destination file. then you also use that for renaming just like the `mv` unix command.

**Comment by TomW1605** [comment]
nvm i worked out how to fix the deleting empty folders. have not tested with a tv show yet so not ready for PR. i also want to work out a way to update the database without losing data.

**Comment by TomW1605** [comment]
ok so this is mostly done but i need to do the last bit which is write a small script to update the database. should i just change the column names for the 3 paths or should i add 3 new ones and remove the old 3? if i update them what pairings? the old names are `ARMPATH`, `RAWPATH` and `MEDIA_DIR` the new ones are `RAW_PATH`, `TRANSCODE_PATH` and `COMPLETED_PATH`. normally raw shouldn't need changing but i also changed the order so that it is in the order following the file flow. im not sure if that matters in the database.
i have pushed the changes to my fork but have not made a PR yet. do you think you could have a look and let me know what you think?

**Comment by 1337-server** [comment]
I've just set up a new Ubuntu machine for testing so i will test these changes hopefully tonight. 

Use Alembric its much simpler than writing a whole script yourself. And its already used for all previous versions of db changes. Personally i would just update to change the names rather than leaving old/unused columns. You can see the previous changes in https://github.com/1337-server/automatic-ripping-machine/tree/v2_devel/arm/migrations/versions

**Comment by TomW1605** [comment]
thanks i will look into it.

**Comment by 1337-server** [comment]
I had a look over the changes and it seems you have modified arm/migrations/versions/c3a3fa694636_.py instead of creating a new upgrade path. This means that its probably fine for new installs, but anyone looking to upgrade would have their install broken because ARM would assume they already have the previous changes so it doesn't need updated. Then ARM would try to call `RAW_PATH, TRANSCODE_PATH and COMPLETED_PATH` but it would error out as those dont exist in older db's

ARM only uses that file when the database is first created, and then it follows the upgrade path set via Alembic. So far it goes c3a3fa694636 -> e688fe04d305 -> 9cae4aa05dd7 (9cae4aa05dd7_create_settingsui_table.py)
You will need to revert the changes to c3a3fa694636_.py and have Alembic create a new upgrade path. It creates the file for you and then you can add your changes to the job table.

These might help you get started
```
cd /opt/arm/arm/migrations

alembic revision -m "issue 17" # This can be blank or a comment
# or 
alembic revision -m "" # This can be blank or a comment
```
This will create a new file in the `arm/migrations/versions/` folder and you can edit and make the changes needed.

**Comment by TomW1605** [comment]
that was a mistake. i did a selective find/replace on the whole project and must have accidentally changed that file without realising. when i work out how to make a new script to update the DB and commit that i will revert the change to `c3a3fa694636_.py`

thanks for looking over the rest of it. i will make that change tonight and commit.

**Comment by TomW1605** [comment]
do i need to create the new folders in the update script? and what should be done with the old ones? rename, delete or ignore?

**Comment by 1337-server** [comment]
I would personally modify `utils.arm_setup()` as that runs before the database update

I would ignore/rename old folders, as deleting them could remove users previous rips.

**Comment by TomW1605** [comment]
ok i will mod `utils.arm_setup()` (i might have already)

what do you think of this mapping for the config variables
`RAWPATH`->`RAW_PATH`
`ARMPATH`->`TRANSCODE_PATH`
`MEDIA_DIR`->`COMPLETED_PATH`

i don't think i will change the actual folder names as that is a bit tricky and might confuse people but we could add a popup on the ui to recommend changing them. i will change the names in the sample config.

**Comment by 1337-server** [comment]
These look good, and make all of them readable.

You can add a flask flash message on the ARMui setup page about changing them.

**Comment by TomW1605** [comment]
ok i have fixed `c3a3fa694636_.py` and added a new version file (committed to my `v2.5.0_dev`). im not sure where best to put the flash, what do you think?

**Comment by 1337-server** [comment]
I'm not sure what's best. 

Either on initial setup or have it check to only run once after a database update. I'm not sure what the best option is really.

**Comment by TomW1605** [comment]
is there some way to pass a temp variable from the migration script? that way it is only triggered the first time after migration.

**Comment by 1337-server** [comment]
Not that I'm aware of, but I'm still new to Alembic. 

You could check/update the contents of the `installed` file. If it still has the previous values update them, and display the message. 

Although a new messages table might be a good way to display messages and it could be used in future for new updates from github or any messages like this in future.

**Comment by TomW1605** [comment]
thats not a bad idea. just a simple table that has an entry for every message that should be displayed at next login. and once they are displayed they are either marked as read in the DB or removed from the table (should save space)

**Comment by TomW1605** [comment]
for now i think i will leave the flash out and then we can develop the message database later. it is getting more and more tedious dealing with merge conflicts and it is not a breaking change. i have submitted a pull request. most of the commits are the merge commits my IDE creates (i am working on turning them off) and there are a few ajax changes in there but i think most of them are already in the master and the commits are just repeated because of the branch and fork mess.

**Comment by 1337-server** [comment]
No problem, the pull looks great!

I will test it and then merge if all is well.

**Comment by TomW1605** [comment]
great i think this can be closed now

**Comment by TomW1605** [comment]
all though squashing the commit has made merging it back to my fork a lot harder. might just revert it and re fork now it is level
