### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user

### ISSUE THREAD

**Issue by jammon** [1337-server/automatic-ripping-machine#29]
### Description
After upgrading from and older version of arm (from the original repo) I tried to create an admin user in the web-ui, and I got this error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.user_id AS user_user_id, user.email AS user_email, user.password AS user_password, user.hash AS user_hash 
FROM user 
WHERE user.email = ?
 LIMIT ? OFFSET ?]
[parameters: ('arm', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

### Environment
OS: Ubuntu 20.04.2 LTS
ARM version v2.5.0_dev

Probably I should have initiated the database, but I cannot find any docs for that.

### Aside
I am thrilled to see that you are actively working on this project. I tried to use it some two years ago but failed due  to many bugs and errors. Also I didn't manage to fix the code myself. 

You did a lot of cleaning up in the documentation and the code, so I started again to try and understand the structure of the code. This has obviously grown over some years from different contributors and is not in a very structured, organized state. So I started refactoring it to clear things up. This makes it easier for me to understand the code and to spot the locations where I might want to change something.

So my question is: Would you be willing to accept pull requests that (hopefully) don't change any functionality, but just clean up the code to make it more understandable? I'd really like to benefit from your future improvement, which I'm sure will come, so I don't want my repo to diverge too much from yours. But in the current state of the code it's not easy to find my way through it, which hampers my motivation to work on it at all. If you allow me to "clean up" old, unstructured, grown code, it would be easier for me and other developers to contribute.

Thank you for reviving this project!

**Comment by 1337-server** [comment]
This error is because the new user table that arm needs hasn't been created.

If you're on the latest commit from this repo, the database upgrade should be automatic when you insert the disc or run the arm command manually. If it doesn't, you can run the same "upgrade" manually via http://WEBSERVER_IP:PORT/setup

This should destroy the current database and create a new database. 

If this doesn't work then you may need to delete the database and visit the /setup again.

I would welcome any PR's.
Reformatting the code to make it easier to read/use is something had been wanting to do, but don't have enough time for at the moment.

**Comment by jammon** [comment]
You were right, I was not on the latest commit. This solved it, you can close this issue.
