### ISSUE TITLE
ARM 2.5.5 doesn't fuzzy match movies with incorrect years

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#91]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
This particular issue may not be an issue, but it is curious. I noticed this happening in this particular fork of ARM, though it seemed to work okay with the original one.

When a movie is matched, but the year is incorrect, ARM will not match it. This seems fair. BUT - in particular cases it might be because the year is the year a collection was published. It seems that (and again, may have been a fluke) that the original from which this repo was forked fuzzy matched these to the first best guess, rather than defaulting on "unidentified" or "Casino Royale (2012)" (which has no appropriate match). 

The examples I've found and are relating here are in a Bond collection. The titles are all correct but the years are off. In version 2.2/2.1, it correctly matched Casino Royale despite its year of 2012 (Casino Royale is a 2006 film). In 2.5.5, it flags all of these as not having a match (or as "Moonraker (2012)" etc.) and they must be manually selected to the first guess from OMDB, even though the titles are correct.

This may instead be a feature request to fuzzy match based on a best guess? Not sure what the best course of action might be. 

**To Reproduce**
1. Insert a movie that has a correct name but incorrect year.
2. Observe ARM will not match it. Again, this may be desirable. But it may be equally desirable to have a "if no match, pick first best match" option.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

ARM 2.5.5_dev

### Log file
I've included the WebUI log as recommended in #85. I have done a few rips since then (with manual matching) so there's a lot, but maybe a lot of hopefully useful information. :)

[WebUI.log](https://github.com/1337-server/automatic-ripping-machine/files/7035662/WebUI.log)

**Comment by 1337-server** [comment]
Could you also attach the full logfile of the job thats not correctly matching ?

**Comment by charmarkk** [comment]
Will add a few tomorrow. Been through this all day with several 007 films, so hopefully lots of good info.

**Comment by charmarkk** [comment]
Here are some to look at, a couple ultimately failed, but got well past the matching step, so are hopefully still usable. :)

[THE_LIVING_DAYLIGHTS.log](https://github.com/1337-server/automatic-ripping-machine/files/7042733/THE_LIVING_DAYLIGHTS.log)
[DIEANOTHERDAY.log](https://github.com/1337-server/automatic-ripping-machine/files/7042735/DIEANOTHERDAY.log)
[A_VIEW_TO_A_KILL_162976099030.log](https://github.com/1337-server/automatic-ripping-machine/files/7042737/A_VIEW_TO_A_KILL_162976099030.log)

**Comment by 1337-server** [comment]
THE_LIVING_DAYLIGHTS - This is due the the way ARM handles blu-rays that don't include the metadata files. if arm cant find `/BDMV/META/DL/bdmt_eng.xml` it will trigger an error raising it out of identification, but will continue processing the disc. It could be possible to fallback to the DVD style of processing as this would sometimes cover this issue but its not something i can work on right now. 

DIEANOTHERDAY - This is another tricky one, and your disc has used possibly the disc production date instead of the film date of release. And since ARM finds a match with the wrong year it assumes this is correct. I cant really think of a way around this issue and you would be rejecting possible valid matches. It would be very tricky to deal with these cases automatically.

A_VIEW_TO_A_KILL - This one is a bug. Ill look into this further as this should be finding a match without the year. And a full result can be found on omdb (http://www.omdbapi.com/?t=A%2BVIEW%2BTO%2BA%2BKILL) Would you be able to disable the suppressed requests here

https://github.com/1337-server/automatic-ripping-machine/blob/76c82dec676e6cfb89b23ee925f574593aac6aec/arm/ripper/logger.py#L46
https://github.com/1337-server/automatic-ripping-machine/blob/76c82dec676e6cfb89b23ee925f574593aac6aec/arm/ripper/logger.py#L47

And re-try the rip ?

**Comment by charmarkk** [comment]
Looks like I get a note in WebUI now "No search results found for Ghost in the Shell - Stand Alone Complex Disc 2 (2017)
**Trying without year**" - is the Trying WIthout Year what I should be seeing now? 

OMDB can't match GITS:SAC anyway. :) Will report back with a more well known movie soon.

**Comment by 1337-server** [comment]
Yes the trying without year is the correct way for arm to deal with disc's it doesnt find any matches for on omdb. ARM should now remove the year then start stripping the last _ (spaces should be replaced with _ ) then keep trying until there are no more underscores left.

Glad to see its back to working the way it should.

**Comment by charmarkk** [comment]
Great! If that's the case, feel free to close when you're satisfied. I'll make sure to give results of a movie in either event. :)
