### ISSUE TITLE
Change the ripping icon to something more appropriate

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#98]
**Is your feature request related to a problem? Please describe.**
As is, the ripping icon is pretty similar to a warning icon. Still throws me off every now and then.

**Describe the solution you'd like**
Add or change the icon to something more visually appropriate, maybe [something like this](https://thenounproject.com/icon.cheese/collection/download-solid/?i=2756159) from the Noun Project. 

**Describe alternatives you've considered**
No need for an alternative really, just a spruce up.

**Are you able to help code/implement this feature ?**
Yeah, most likely if it's just some HTML direction. :) Just not sure if this is something built into the stylesheets etc. that can't easily be mucked with.

**Additional context**
Yet another thought that came to mind about visual polish, is all. :)

**Comment by 1337-server** [comment]
Unfortunately, due to the licensing restrictions on that site and how the icons are distributed, it would be breaking the site's license to add them to the ARM repo. They don't allow redistribution even if the software is free.

But adding it to your own install would be as simple as downloading the icon and renaming it to ripping.png. You could then put it in the folder `/opt/arm/arm/ui/static/img/`

Then refresh your browser. I will eventually get around to making one that fits more with the rest of the icons. I just have very little time at the moment.

**Comment by charmarkk** [comment]
Oh that makes more than enough sense, and that was just a suggestion of what something might look like. Maybe I'll see if I can find something fitting and free to use and PR it, take that off the plate of duties. :) 

Just a continuity thought!

**Comment by 1337-server** [comment]
That would be great thanks!

**Comment by 1337-server** [comment]
New icon added that more closely matches the other icons.
